version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - /postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # mysql:
    # image: mysql
    # command: --default-authentication-plugin=mysql_native_password
    # restart: always
    # environment:
      # MYSQL_DATABASE: ${DB_NAME}
      # MYSQL_USER: root
      # MYSQL_ROOT_PASSWOR: ${DB_PASSWORD}
      # MYSQL_PORT: 8080
    # ports:
      # - "8080:8080"
    # volumes:
      # - /mysql_data:/var/lib/mysql

  # phpmyadmin:
    # image: phpmyadmin/phpmyadmin
    # environment:
      # - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      # - PMA_HOST=mysql
    # ports:
      # - "8000:80"
